### ISSUE TITLE
Fix README.md

### ISSUE THREAD

**Issue by thezealousfool** [UnivNet/backend#2]
The README is all messed up. Also I don't think it is a good idea to have the passwords displayed in the README

**Comment by thezealousfool** [comment]
Changed it in https://github.com/UnivNet/backend/commit/1a4ca304054803d9844d7e2929dfb44afc5e1656
Feel free to comment

**Comment by say4n** [comment]
Once committed, it's no use changing the readme, it's already out there. We'll have to change the db password.

**Comment by thezealousfool** [comment]
Yes, we need to change the db password.
Mark this issue as resolved once the db password is changed.

**Comment by Sayan98** [comment]
Mark as resolved after #7 @vivek-roy
